ALTER TABLE users
ADD COLUMN name VARCHAR(255),
ADD COLUMN last_name VARCHAR(255),
ADD COLUMN age INTEGER,
ADD COLUMN gender VARCHAR(50),
ADD COLUMN height DECIMAL(5,2),
ADD COLUMN weight DECIMAL(5,2),
ADD COLUMN disease_history TEXT;